INSERT INTO QUOTE VALUES(1, 'Kevin Kruse',23,'Life is not about getting and having, it is about giving and being.','kindness');
INSERT INTO QUOTE VALUES(2, 'Napoleon Hill',67,'Whatever the mind of man can conceive and believe, it can achieve.','believing');
INSERT INTO QUOTE VALUES(3, 'Albert Einstein',19,'Strive not to be a success, but rather to be of value.','Success');
INSERT INTO QUOTE VALUES(4, 'Robert Frost',8,'Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.','impossible');
INSERT INTO QUOTE VALUES(5, 'Florence Nightingale',234,'I attribute my success to this: I never gave or took any excuse.','no excuse');
INSERT INTO QUOTE VALUES(6, 'Wayne Gretzky',122,'You miss 100% of the shots you do not take.','Trying');
INSERT INTO QUOTE VALUES(7, 'Michael Jordan',98,'I have missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I have been trusted to take the game winning shot and missed. I have failed over and over and over again in my life. And that is why I succeed.','trying');
INSERT INTO QUOTE VALUES(8, 'Amelia Earhart',67,'The most difficult thing is the decision to act, the rest is merely tenacity.','start');
INSERT INTO QUOTE VALUES(9, 'Babe Ruth',78,'Every strike brings me closer to the next home run.','believing');
INSERT INTO QUOTE VALUES(10, 'W. Clement Stone',4,'Definiteness of purpose is the starting point of all achievement.','start');
INSERT INTO QUOTE VALUES(11, 'Kevin Kruse',98,'We must balance conspicuous consumption with conscious capitalism.','strategy');
INSERT INTO QUOTE VALUES(12, 'John Lennon',77,'Life is what happens to you while you’re busy making other plans.','All is good');
INSERT INTO QUOTE VALUES(13, 'Earl Nightingale',56,'We become what we think about.','believing');
INSERT INTO QUOTE VALUES(14, 'Mark Twain',89,'Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.','All is good');
INSERT INTO QUOTE VALUES(15, 'Charles Swindoll',22,'Life is 10% what happens to me and 90% of how I react to it.','strategy');
INSERT INTO QUOTE VALUES(16, 'Alice Walker',67,'The most common way people give up their power is by thinking they don’t have any.','believing');
INSERT INTO QUOTE VALUES(17, 'Buddha',2234,'The mind is everything. What you think you become.','believing');
INSERT INTO QUOTE VALUES(18, 'Chinese Proverb',859,'The best time to plant a tree was 20 years ago. The second best time is now.','start');
INSERT INTO QUOTE VALUES(19, 'Socrates',109,'An unexamined life is not worth living.','no excuse');
INSERT INTO QUOTE VALUES(20, 'Woody Allen',78,'Eighty percent of success is showing up.','Success');
INSERT INTO QUOTE VALUES(21, 'Steve Jobs',109,'Your time is limited, so don’t waste it living someone else’s life.','no excuse');
INSERT INTO QUOTE VALUES(22, 'Vince Lombardi',109,'Winning isn’t everything, but wanting to win is.','Trying');
INSERT INTO QUOTE VALUES(23, 'Stephen Covey',569,'I am not a product of my circumstances. I am a product of my decisions.','believing');
INSERT INTO QUOTE VALUES(24, 'Pablo Picasso',567,'Every child is an artist.  The problem is how to remain an artist once he grows up..','believing');
INSERT INTO QUOTE VALUES(25, 'Christopher Columbus',67,'You can never cross the ocean until you have the courage to lose sight of the shore.','strategy');